apiVersion: v1
kind: Service
metadata:
    name: posts-srv
spec:
    type: NodePort #default is ClusterIP, we are using node port for only test purpose.
    selector:
        app: posts
    ports:
        - name: posts
          protocol: TCP
          port: 4000
          targetPort: 4000
